"""Django settings for learney_web project.

Generated by 'django-admin startproject' using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import json
import os
from pathlib import Path

import yaml

from learney_web.utils import get_concept_names, get_predecessor_dict

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

with open("dev_env.yaml", "r") as env_file:
    dev_secrets_dict = yaml.load(env_file, Loader=yaml.Loader)

SECRET_KEY = dev_secrets_dict["SECRET_KEY"]

SLACK_TOKEN = dev_secrets_dict["SLACK_TOKEN"]
NOTION_KEY = dev_secrets_dict["NOTION_KEY"]
AWS_CREDENTIALS = dev_secrets_dict["AWS_CREDENTIALS"]

PYTHON_ENV = os.environ.get("PYTHON_ENV", "dev")
DEBUG = PYTHON_ENV not in ["production", "staging"]

ALLOWED_HOSTS = [
    # prod url
    "app.learney.me",
    # prod aws
    "learneyapp-env.eba-ed9hpad3.us-west-2.elasticbeanstalk.com",
    "172.31.8.139",
    "172.31.13.26",
    # staging url
    "staging.learney.me",
    # staging aws
    "staging-learneyapp-env.eba-ed9hpad3.us-west-2.elasticbeanstalk.com",
    "172.31.39.124",
    "172.31.18.129",
    "44.233.38.189",
    # localhost
    "127.0.0.1",
    "0.0.0.0",
]

# Log output to a log file stored in the container
DEBUG_PROPAGATE_EXCEPTIONS = True
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": {
#         "verbose": {
#             "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
#             "datefmt": "%d/%b/%Y %H:%M:%S",
#         },
#         "simple": {"format": "%(levelname)s %(message)s"},
#     },
#     "handlers": {
#         "file": {
#             "level": "DEBUG",
#             "class": "logging.FileHandler",
#             "filename": "learney.log",
#             "formatter": "verbose",
#         },
#     },
#     "loggers": {
#         "django": {
#             "handlers": ["file"],
#             "propagate": True,
#             "level": "DEBUG",
#         },
#         "MYAPP": {
#             "handlers": ["file"],
#             "level": "DEBUG",
#         },
#     },
# }

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "social_django",
    "auth0login",
    "learney_backend",
    "goals",
    "knowledge_maps",
    "learned",
    "link_clicks",
    "page_visits",
    "question_bot",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "learney_web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "learney_web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if "RDS_DB_NAME" in os.environ:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": os.environ["RDS_DB_NAME"],
            "USER": os.environ["RDS_USERNAME"],
            "PASSWORD": os.environ["RDS_PASSWORD"],
            "HOST": os.environ["RDS_HOSTNAME"],
            "PORT": os.environ["RDS_PORT"],
        }
    }
else:
    DATABASES = {"default": dev_secrets_dict["DATABASES"]}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Set to use HTTPS if on production server
if PYTHON_ENV in ["production", "staging"]:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 518400
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = "/static/"
STATICFILES_DIRS = [str(BASE_DIR.parent / "assets")]
STATIC_ROOT = str(BASE_DIR / "static")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Load content json in once
with open(f"{STATICFILES_DIRS[0]}/positions_map_v013.json", "r") as content_json_file:
    CONTENT_JSON = json.load(content_json_file)

ORIG_MAP_PREDECESSOR_DICT = get_predecessor_dict(CONTENT_JSON["edges"])
ORIG_MAP_CONCEPT_NAMES = get_concept_names(CONTENT_JSON)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# For auth0
with open("auth0_conf.yaml", "r") as auth0_conf_file:
    auth0_conf = yaml.load(auth0_conf_file, Loader=yaml.Loader)


SOCIAL_AUTH_TRAILING_SLASH = False  # Remove trailing slash from routes
SOCIAL_AUTH_AUTH0_DOMAIN = auth0_conf["SOCIAL_AUTH_AUTH0_DOMAIN"]
SOCIAL_AUTH_AUTH0_KEY = auth0_conf[PYTHON_ENV]["SOCIAL_AUTH_AUTH0_KEY"]
SOCIAL_AUTH_AUTH0_SECRET = auth0_conf[PYTHON_ENV]["SOCIAL_AUTH_AUTH0_SECRET"]

SOCIAL_AUTH_AUTH0_SCOPE = ["openid", "profile", "email"]

AUTHENTICATION_BACKENDS = {
    "auth0login.auth0backend.Auth0",
    "django.contrib.auth.backends.ModelBackend",
}

LOGIN_URL = "/login/auth0"
LOGIN_REDIRECT_URL = "/dashboard"
