# Generated by Django 4.0.2 on 2022-02-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questiontemplate",
            name="active",
            field=models.BooleanField(
                default=False,
                help_text="If questions from the template should be used on the live site - broken questions should be deactivated until they're fixed!",
            ),
        ),
    ]
