# Generated by Django 3.2.2 on 2022-01-27 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_maps", "0007_add_concepts_from_questions_map"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionset",
            name="concept",
            field=models.ForeignKey(
                default=None,
                help_text="The concept that the question set corresponds to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_sets",
                to="knowledge_maps.concept",
            ),
            preserve_default=False,
        ),
    ]
