# Generated by Django 4.0.2 on 2022-02-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_alter_questiontemplate_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionbatch",
            name="time_taken_to_complete",
        ),
    ]
