# Generated by Django 4.0.2 on 2022-02-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_remove_questionbatch_time_taken_to_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbatch",
            name="time_taken_to_complete",
            field=models.DurationField(
                default=None,
                help_text="Time after the question batch was started that it was completed",
                null=True,
            ),
        ),
    ]
