# Generated by Django 3.2.2 on 2021-08-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_visits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevisitmodel",
            name="page_extension",
            field=models.TextField(default="", help_text="URL extension of the page visited"),
        ),
    ]
