# Generated by Django 3.2.2 on 2021-09-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_visits", "0002_pagevisitmodel_page_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevisitmodel",
            name="session_id",
            field=models.TextField(
                blank=True, editable=False, help_text="session_key of the session"
            ),
        ),
    ]
