# Generated by Django 3.2.2 on 2021-09-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page_visits", "0003_pagevisitmodel_session_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagevisitmodel",
            old_name="visit_time",
            new_name="timestamp",
        ),
    ]
