# Generated by Django 3.2.2 on 2021-10-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page_visits", "0004_rename_visit_time_pagevisitmodel_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagevisitmodel",
            name="session_id",
            field=models.TextField(blank=True, help_text="session_key of the session"),
        ),
    ]
