# Generated by Django 3.2.2 on 2021-06-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClickModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('user_id', models.TextField()),
                ('click_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
