# Generated by Django 3.2.2 on 2021-09-27 19:58

from uuid import UUID

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("link_clicks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkclickmodel",
            name="map_uuid",
            field=models.UUIDField(
                default=UUID("015a52d3-1e58-47d6-abf4-35a60c0928ab"),
                editable=False,
                help_text="UUID of the map this link click corresponds to",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="linkclickmodel",
            name="session_id",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="session_key of the session the link was clicked in",
            ),
        ),
    ]
