# Generated by Django 3.2.2 on 2021-10-01 14:43

from django.db import migrations


def link_click_migration_4(apps, schema_editor):
    LinkClickModel = apps.get_model("link_clicks", "LinkClickModel")
    ContentLinkPreview = apps.get_model("learney_backend", "ContentLinkPreview")

    link_clicks = LinkClickModel.objects.filter(concept_id=None)
    print(f"Number of link clicks with no concept_id before migration: {link_clicks.count()}")
    for link_click in link_clicks:
        link_previews = ContentLinkPreview.objects.filter(
            map_uuid=link_click.map_uuid,
            url=link_click.url,
        )
        if link_previews.count() == 0:
            continue

        link_previews_before_click = link_previews.filter(
            preview_last_updated__lt=link_click.timestamp
        )

        if link_previews_before_click.count() > 0:
            chosen_link_preview = link_previews_before_click.latest("preview_last_updated")
        else:
            chosen_link_preview = link_previews.earliest("preview_last_updated")
        link_click.content_link_preview_id = chosen_link_preview.pk
        link_click.concept_id = chosen_link_preview.concept_id
        link_click.save()
    print(
        f"Number of link clicks with no concept_id after migration: {LinkClickModel.objects.filter(concept_id=None).count()}"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("link_clicks", "0004_add_concept_id"),
        ("learney_backend", "0011_concept_id_data"),
    ]

    operations = [
        migrations.RunPython(link_click_migration_4, reverse_code=migrations.RunPython.noop)
    ]
