# Generated by Django 3.2.2 on 2021-09-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_maps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgemapmodel",
            name="allow_suggestions",
            field=models.BooleanField(
                default=True, help_text="Whether to allow suggestions on this map"
            ),
        ),
    ]
