# Generated by Django 3.2.2 on 2022-01-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_maps", "0004_fix_underscore_issue_name_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgemapmodel",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the knowledge map shown in top left corner",
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name="knowledgemapmodel",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Title of the knowledge map shown in top left corner",
                max_length=32,
            ),
        ),
    ]
