# Generated by Django 4.0.2 on 2022-02-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_maps", "0007_add_concepts_from_questions_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="direct_prerequisites",
            field=models.ManyToManyField(
                help_text="The direct prerequisites of this concept",
                related_query_name="direct_successor",
                to="knowledge_maps.Concept",
            ),
        ),
    ]
