# Generated by Django 3.2 on 2021-05-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentLinkPreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concept", models.TextField()),
                ("url", models.URLField(unique=True)),
                ("last_retrieved", models.DateTimeField(auto_now=True)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="ContentVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("vote", models.BooleanField()),
                ("vote_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
