# Generated by Django 3.2 on 2021-05-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learney_backend", "0002_auto_20210516_1532"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentvote",
            name="url",
            field=models.URLField(),
        ),
    ]
