# Generated by Django 3.2.2 on 2021-06-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learney_backend", "0003_alter_contentvote_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentlinkpreview",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="contentlinkpreview",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contentlinkpreview",
            name="title",
            field=models.TextField(blank=True),
        ),
    ]
