# Generated by Django 3.2.2 on 2021-08-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learney_backend", "0006_alter_contentvote_concept"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentlinkpreview",
            old_name="preview_last_retrieved",
            new_name="preview_last_updated",
        ),
        migrations.AddField(
            model_name="contentlinkpreview",
            name="map_name",
            field=models.TextField(default="original_map"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contentlinkpreview",
            name="url",
            field=models.URLField(),
        ),
    ]
