# Generated by Django 3.2.2 on 2021-08-10 10:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learney_backend", "0006_alter_contentvote_concept"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentlinkpreview",
            old_name="preview_last_retrieved",
            new_name="preview_last_updated",
        ),
        migrations.AddField(
            model_name="contentlinkpreview",
            name="map_uuid",
            field=models.UUIDField(
                default=uuid.UUID("015a52d3-1e58-47d6-abf4-35a60c0928ab"),
                editable=False,
                help_text="UUID of the map this content link corresponds to",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contentlinkpreview",
            name="url",
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name="contentvote",
            name="map_uuid",
            field=models.UUIDField(
                default=uuid.UUID("015a52d3-1e58-47d6-abf4-35a60c0928ab"),
                editable=False,
                help_text="UUID of the map this content link corresponds to",
            ),
            preserve_default=False,
        ),
    ]
