# Generated by Django 3.2.2 on 2021-09-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learney_backend", "0007_auto_20210810_1003"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentvote",
            name="session_id",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="session_key of the session in which the vote was made",
            ),
        ),
    ]
