# Generated by Django 3.2.2 on 2021-09-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learney_backend", "0008_contentvote_session_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentvote",
            old_name="vote_time",
            new_name="timestamp",
        ),
    ]
