# Generated by Django 3.2.2 on 2021-10-02 08:35

from django.db import migrations, models

import learney_web.validators


class Migration(migrations.Migration):

    dependencies = [
        ("learney_backend", "0009_rename_vote_time_contentvote_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentlinkpreview",
            name="concept_id",
            field=models.CharField(
                help_text="ID of the concept the link corresponds to (defined in the map json)",
                max_length=8,
                null=True,
                validators=[learney_web.validators.validate_numeric],
            ),
        ),
        migrations.AlterField(
            model_name="contentlinkpreview",
            name="concept",
            field=models.TextField(help_text="Name of the concept the link corresponds to"),
        ),
        migrations.AlterField(
            model_name="contentlinkpreview",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the link preview - shows below the title of the content",
            ),
        ),
        migrations.AlterField(
            model_name="contentlinkpreview",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="Thumbnail image of the link preview", null=True
            ),
        ),
        migrations.AlterField(
            model_name="contentlinkpreview",
            name="title",
            field=models.TextField(
                blank=True,
                help_text="Title of the link preview - shows as the title of the item of content",
            ),
        ),
        migrations.AlterField(
            model_name="contentlinkpreview",
            name="url",
            field=models.URLField(help_text="The URL of the link clicked"),
        ),
    ]
