# Generated by Django 3.2.2 on 2021-10-01 14:42

import json

from django.db import migrations

from knowledge_maps.views import retrieve_map


def data_migration_content_preview(apps, schema_editor):
    ContentLinkPreview = apps.get_model("learney_backend", "ContentLinkPreview")
    KnowledgeMapModel = apps.get_model("knowledge_maps", "KnowledgeMapModel")
    for map in KnowledgeMapModel.objects.all():
        map_json = json.loads(retrieve_map(map).decode("utf-8"))
        for entry in ContentLinkPreview.objects.filter(concept_id=None, map_uuid=map.unique_id):
            for node in map_json["nodes"]:
                if (
                    entry.url in node["data"].get("urls", [])
                    or entry.concept == node["data"]["name"]
                ):
                    entry.concept_id = node["data"]["id"]
                    entry.save()
                    break


class Migration(migrations.Migration):

    dependencies = [
        ("learney_backend", "0010_add_concept_id"),
    ]

    operations = [
        migrations.RunPython(data_migration_content_preview, reverse_code=migrations.RunPython.noop)
    ]
