# Generated by Django 3.2.2 on 2021-10-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learney_backend", "0011_concept_id_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentvote",
            name="session_id",
            field=models.TextField(
                blank=True, help_text="session_key of the session in which the vote was made"
            ),
        ),
    ]
