# Generated by Django 3.2.2 on 2021-10-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learney_backend", "0013_alter_contentvote_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentvote",
            name="vote",
            field=models.BooleanField(
                help_text="The direction of the vote on the link - None is invalid (broken data), True is upvote and False is downvote",
                null=True,
            ),
        ),
    ]
