# Generated by Django 3.2.2 on 2021-11-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learney_backend", "0014_alter_contentvote_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentlinkpreview",
            name="url",
            field=models.URLField(help_text="The resource URL", max_length=1024),
        ),
    ]
