# Generated by Django 3.2.2 on 2021-12-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learney_backend", "0016_migrate_old_data_to_mixpanel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentvote",
            name="concept",
            field=models.TextField(help_text="Name of the concept the content URL corresponds to"),
        ),
        migrations.AlterField(
            model_name="contentvote",
            name="url",
            field=models.URLField(help_text="Resource URL voted on"),
        ),
    ]
