# Generated by Django 3.2.2 on 2022-01-05 18:10
from typing import List, Tuple

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("nickname", models.CharField(blank=True, max_length=255)),
                ("given_name", models.CharField(blank=True, max_length=255)),
                ("family_name", models.CharField(blank=True, max_length=255)),
                ("picture", models.URLField()),
                ("locale", models.CharField(blank=True, max_length=8)),
            ],
        ),
    ]
