# Generated by Django 3.2.2 on 2022-01-05 18:10
import json
from typing import Any, Dict

from django.db import migrations

import boto3
from learney_web.settings import AWS_CREDENTIALS, IS_PROD, mixpanel

S3_FILENAME = "dev-3sm9ewzj.json"


def user_data_download_to_mixpanel_format(user_data: Dict) -> Dict[str, Any]:
    return {
        "Email Verified": user_data["Email Verified"],
        "ID": user_data["Id"],
        "$name": user_data["Name"],
        "$email": user_data["Email"],
    }


def get_users():
    # GET json file from S3
    s3 = boto3.resource(
        "s3",
        aws_access_key_id=AWS_CREDENTIALS["ACCESS_ID"],
        aws_secret_access_key=AWS_CREDENTIALS["SECRET_KEY"],
    )
    response = s3.Object("learney-prod", S3_FILENAME).get()
    return json.loads(response["Body"].read())


def upload_auth0_data_to_mixpanel(apps, schema_editor):
    users = get_users()
    emails_seen = {}

    for user_data in users:
        if IS_PROD:
            if user_data["Email"] not in emails_seen:
                properties = user_data_download_to_mixpanel_format(user_data)
                mixpanel.people_set(user_data["Id"], properties, meta={"$ignore_time": True})
            else:
                mixpanel.alias(user_data["Id"], emails_seen[user_data["Email"]])

        emails_seen[user_data["Email"]] = user_data["Id"]


class Migration(migrations.Migration):

    initial = True

    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.RunPython(upload_auth0_data_to_mixpanel, reverse_code=migrations.RunPython.noop),
    ]
