# Generated by Django 3.2.2 on 2022-01-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learney_backend", "0019_contentvote_content_link_preview"),
        ("accounts", "0003_get_users_from_auth0"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="checked_content_links",
            field=models.ManyToManyField(
                help_text="The content links that this user has checked",
                related_name="checked_by",
                to="learney_backend.ContentLinkPreview",
            ),
        ),
    ]
