# Generated by Django 4.0.2 on 2022-02-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learney_backend", "0020_ensure_all_contentlinkpreviews_exist"),
        ("accounts", "0006_alter_user_family_name_alter_user_given_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="checked_content_links",
            field=models.ManyToManyField(
                blank=True,
                help_text="The content links that this user has checked",
                related_name="checked_by",
                to="learney_backend.ContentLinkPreview",
            ),
        ),
    ]
