# Generated by Django 4.0.2 on 2022-02-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_checked_content_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="questions_streak",
            field=models.IntegerField(
                default=0, help_text="How many days in a row they've completed a question batch"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="utc_tz_difference",
            field=models.FloatField(
                default=0,
                help_text="The user's timezone relative to UTC in hours. E.g. 4 = UTC+4 and -5 = UTC-5",
            ),
        ),
    ]
