# Generated by Django 3.2.2 on 2021-08-19 10:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalmodel",
            name="map_uuid",
            field=models.UUIDField(
                default=uuid.UUID("015a52d3-1e58-47d6-abf4-35a60c0928ab"),
                editable=False,
                help_text="UUID of the map this goal corresponds to",
            ),
            preserve_default=False,
        ),
    ]
