# Generated by Django 3.2.2 on 2021-09-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_goalmodel_map_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalmodel",
            name="session_id",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="session_key of the session the goal was set in",
            ),
        ),
    ]
