# Generated by Django 3.2.2 on 2021-09-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0003_goalmodel_session_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goalmodel",
            old_name="last_updated",
            new_name="timestamp",
        ),
    ]
