# Generated by Django 3.2.2 on 2021-10-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0004_rename_last_updated_goalmodel_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalmodel",
            name="session_id",
            field=models.TextField(
                blank=True, help_text="session_key of the session the goal was set in"
            ),
        ),
    ]
