# Generated by Django 3.2.2 on 2021-12-22 14:49

import django.db.models.deletion
from django.db import migrations, models


def populate_map_field(apps, schema_editor):
    KnowledgeMapModel = apps.get_model("knowledge_maps", "KnowledgeMapModel")
    GoalModel = apps.get_model("goals", "GoalModel")
    for goal_entry in GoalModel.objects.all():
        goal_entry.map = KnowledgeMapModel.objects.get(unique_id=goal_entry.map_uuid)
        goal_entry.save()


def populate_map_uuid_field(apps, schema_editor):
    GoalModel = apps.get_model("goals", "GoalModel")
    for goal_entry in GoalModel.objects.all():
        goal_entry.map_uuid = goal_entry.map.unique_id
        goal_entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_maps", "0004_fix_underscore_issue_name_id"),
        ("goals", "0006_migrate_old_data_to_mixpanel"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalmodel",
            name="map",
            field=models.ForeignKey(
                help_text="Map this goal corresponds to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals_set",
                to="knowledge_maps.knowledgemapmodel",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="goalmodel",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(populate_map_field, reverse_code=populate_map_uuid_field),
        migrations.RemoveField(
            model_name="goalmodel",
            name="map_uuid",
        ),
        migrations.AlterField(
            model_name="goalmodel",
            name="map",
            field=models.ForeignKey(
                help_text="Map this goal corresponds to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals_set",
                to="knowledge_maps.knowledgemapmodel",
            ),
        ),
    ]
