# Generated by Django 3.2.2 on 2021-09-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="ButtonPressModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "user_id",
                    models.TextField(help_text="User ID of the user who pressed the button"),
                ),
                (
                    "session_id",
                    models.TextField(
                        help_text="session_key of the session the button was pressed in"
                    ),
                ),
                (
                    "page_extension",
                    models.TextField(
                        help_text="Extension of the page the user was on when the button was pressed"
                    ),
                ),
                (
                    "button_name",
                    models.TextField(
                        choices=[
                            ("log-in", " Log In"),
                            ("log-out", "Log Out"),
                            ("profile-image-button", "Profile Image"),
                            ("make-suggestion", "Make Suggestion"),
                            ("content-suggestion", "Content Suggestion"),
                            ("open-intro", "Open Intro"),
                            ("close-intro", "Close Intro"),
                            ("close-concept", "Close Concept"),
                            ("next-intro", "Next Intro Slide"),
                            ("prev-intro", "Previous Intro Slide"),
                            ("save-layout", "Save Layout"),
                            ("reset-layout", "Reset Layout"),
                            ("run-dagre", "Run Dagre"),
                            ("reset-progress", "Reset Progress"),
                            ("reset-pan", "Reset Pan"),
                            ("feedback-button", "Feedback Button"),
                            ("slack-button", "Slack Button"),
                        ],
                        help_text="Name of the button pressed",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
