# Generated by Django 3.2.2 on 2021-09-30 19:49
from datetime import datetime

import requests
from django.db import migrations

from button_presses.models import ButtonPressModel
from learney_web.settings import IS_PROD, MIXPANEL_KEY


def send_entries_to_mixpanel(apps, schema_editor):
    if not IS_PROD:
        return
    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "Authorization": "Basic YmFja2VuZF8zLmQyZGVhYS5tcC1zZXJ2aWNlLWFjY291bnQ6Qm9aT055NWp5cXZVOURCRVdPSDVGclQ5QXlMa2dOYnU=",
    }
    url = "https://api.mixpanel.com/import?strict=1&project_id=2572468"
    batch = []
    for entry in ButtonPressModel.objects.filter():
        batch.append(
            {
                "event": "Button Press",
                "properties": {
                    "Button Name": entry.button_name,
                    "time": int(entry.timestamp.timestamp()),
                    "distinct_id": entry.user_id,
                    "$insert_id": str(entry.pk),
                    "URL": f"https://app.learney.me{entry.page_extension}",
                    "token": MIXPANEL_KEY,
                },
            }
        )
        if len(batch) == 50:
            response = requests.post(headers=headers, url=url, json=batch)
            print(response.text)
            batch = []
    if batch:
        response = requests.post(headers=headers, url=url, json=batch)
        print(response.text)


class Migration(migrations.Migration):
    initial = True
    dependencies = [("button_presses", "0001_initial")]  # type: ignore

    operations = [
        migrations.RunPython(send_entries_to_mixpanel, reverse_code=migrations.RunPython.noop),
    ]
