# Generated by Django 3.2.2 on 2021-09-30 19:49
from datetime import datetime

import requests
from django.db import migrations

from knowledge_maps.models import KnowledgeMapModel
from learned.models import LearnedModel
from learney_web.settings import IS_PROD, MIXPANEL_KEY


def send_entries_to_mixpanel(apps, schema_editor):
    if not IS_PROD:
        return
    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "Authorization": "Basic YmFja2VuZF8zLmQyZGVhYS5tcC1zZXJ2aWNlLWFjY291bnQ6Qm9aT055NWp5cXZVOURCRVdPSDVGclQ5QXlMa2dOYnU=",
    }
    url = "https://api.mixpanel.com/import?strict=1&project_id=2572468"
    map_to_extension = {
        str(map_entry.unique_id): map_entry.url_extension
        for map_entry in KnowledgeMapModel.objects.all()
    }

    batch = []
    for entry in LearnedModel.objects.filter(
        timestamp__lt=datetime(year=2021, month=11, day=24, hour=14, minute=45)
    ):
        batch.append(
            {
                "event": "Learned",
                "properties": {
                    "learned_state": entry.learned_concepts,
                    "map_uuid": str(entry.map_uuid),
                    "session_id": entry.session_id,
                    "time": int(entry.timestamp.timestamp()),
                    "distinct_id": entry.user_id,
                    "$insert_id": str(entry.pk),
                    "map_url_extension": map_to_extension[str(entry.map_uuid)],
                    "token": MIXPANEL_KEY,
                },
            }
        )
        if len(batch) == 50:
            response = requests.post(headers=headers, url=url, json=batch)
            print(response.text)
            batch = []
    if batch:
        response = requests.post(headers=headers, url=url, json=batch)
        print(response.text)


class Migration(migrations.Migration):
    initial = True
    dependencies = [("learned", "0005_alter_learnedmodel_session_id")]  # type: ignore

    operations = [
        migrations.RunPython(send_entries_to_mixpanel, reverse_code=migrations.RunPython.noop),
    ]
