# Generated by Django 3.2.2 on 2021-12-22 14:49

import django.db.models.deletion
from django.db import migrations, models


def populate_map_field(apps, schema_editor):
    KnowledgeMapModel = apps.get_model("knowledge_maps", "KnowledgeMapModel")
    LearnedModel = apps.get_model("learned", "LearnedModel")
    for learned_entry in LearnedModel.objects.all():
        learned_entry.map = KnowledgeMapModel.objects.get(unique_id=learned_entry.map_uuid)
        learned_entry.save()


def populate_map_uuid_field(apps, schema_editor):
    LearnedModel = apps.get_model("learned", "LearnedModel")
    for learned_entry in LearnedModel.objects.all():
        learned_entry.map_uuid = learned_entry.map.unique_id
        learned_entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_maps", "0004_fix_underscore_issue_name_id"),
        ("learned", "0006_migrate_old_data_to_mixpanel"),
    ]

    operations = [
        migrations.AddField(
            model_name="learnedmodel",
            name="map",
            field=models.ForeignKey(
                help_text="Map this learned dictionary corresponds to",
                related_name="learned",
                on_delete=django.db.models.deletion.CASCADE,
                to="knowledge_maps.knowledgemapmodel",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="learnedmodel",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(populate_map_field, reverse_code=populate_map_uuid_field),
        migrations.RemoveField(
            model_name="learnedmodel",
            name="map_uuid",
        ),
        migrations.AlterField(
            model_name="learnedmodel",
            name="map",
            field=models.ForeignKey(
                help_text="Map this learned dictionary corresponds to",
                related_name="learned",
                on_delete=django.db.models.deletion.CASCADE,
                to="knowledge_maps.knowledgemapmodel",
            ),
        ),
    ]
